name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
input:
  caching:
    description: 'Wether to cache dependencies or not.'
    required: false
    default: 'true'
output:
  used-cache: 
    description: 'Wether the cache was used.'
    value: ${{ steps.install.output.cache }}
runs:
  using: 'composite'
  steps: 
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || input.caching != 'true'
      id: install
      run: |
        npm ci
        echo "cache='${{ input.caching }}'" >> $GITHUB_OUTPUT
      shell: bash